plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.example.lav_digitalizacija'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.lav_digitalizacija"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:34.9.0')
    implementation "com.google.firebase:firebase-appcheck-debug"
    // Firebase (bez verzija jer BoM upravlja)
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-functions'
    implementation 'com.google.firebase:firebase-database'
    implementation 'com.google.firebase:firebase-storage'
    implementation 'com.google.firebase:firebase-common'
    // AndroidX
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.activity:activity:1.10.1'

    // Gson
    implementation 'com.google.code.gson:gson:2.9.0'

    // Glide
    implementation 'com.github.bumptech.glide:glide:4.15.1'
    implementation 'com.google.android.gms:play-services-code-scanner:16.1.0'
    implementation 'com.google.firebase:firebase-inappmessaging:22.0.2'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.15.1'

    //QR CODE IMPLEMENTATION
    implementation 'com.google.android.gms:play-services-mlkit-barcode-scanning:18.3.1'


    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    //FIREBASE ANONYMOUS SIGN-IN
    implementation(platform("com.google.firebase:firebase-bom:34.11.0"))
    implementation("com.google.firebase:firebase-auth")
}